### ISSUE TITLE
Todo List Client Management

### ISSUE THREAD

**Issue by lukesUbuntu** [webkitz/virtualmin_blesta#11]
Would not install till the **Need to fix** & **To Be Done** has been completed
 
 ## Need to fix  :
- [x] Server Status (fixed)
- [x] Mail accounts (fixed #19)
- [x] Databases (fixed)
- [x] Install Scripts (fixed on #23)
- [ ] Backups
- [ ] fix tab rendering (eg some tabs require page reload to see clients changes)

 ## To Be Done  :
- [x] Add virtualmin server connection test before saving (#22)
- [ ] DNS editor (currently working on #14)
- [ ] Cloudflare Integration (DNS syncing option)
- [ ] FTP Accounts
- [ ] Manage Sub Domains
- [ ] Manage PHP versions (set php version for domain)
- [ ] Admin & Client wiki (screenshots)

 ## Maybe Added : (not sure if a client needs to)
- [ ] Manage Website Options
- [ ] Manage SSL
- [ ] Manage Cron jobs 
- [ ] Reseller Options
